// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrbxsoUHfB4pB1ju4P6hAQE4mR2z3adxk',
    appId: '1:42116415858:web:ad21f85709690b82115deb',
    messagingSenderId: '42116415858',
    projectId: 'trash-to-cash-20037',
    authDomain: 'trash-to-cash-20037.firebaseapp.com',
    databaseURL: 'https://trash-to-cash-20037-default-rtdb.firebaseio.com',
    storageBucket: 'trash-to-cash-20037.appspot.com',
    measurementId: 'G-BD92J0JXZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAxtz7f4cRHSY_borZJmI5mmzFQqhl1FI',
    appId: '1:42116415858:android:33e775b22d800996115deb',
    messagingSenderId: '42116415858',
    projectId: 'trash-to-cash-20037',
    databaseURL: 'https://trash-to-cash-20037-default-rtdb.firebaseio.com',
    storageBucket: 'trash-to-cash-20037.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAyutfpfmRAIv9m8uyioEeCfF1biw2YPM',
    appId: '1:42116415858:ios:9d57f2cfe5dc0ba9115deb',
    messagingSenderId: '42116415858',
    projectId: 'trash-to-cash-20037',
    databaseURL: 'https://trash-to-cash-20037-default-rtdb.firebaseio.com',
    storageBucket: 'trash-to-cash-20037.appspot.com',
    androidClientId: '42116415858-evk927j764gi4ui7jk67kmvb26avdls1.apps.googleusercontent.com',
    iosClientId: '42116415858-ipcf2tn8etvr24ghvctdjoufhbfif08h.apps.googleusercontent.com',
    iosBundleId: 'com.example.trashToCashFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAyutfpfmRAIv9m8uyioEeCfF1biw2YPM',
    appId: '1:42116415858:ios:f9f839ca206336ba115deb',
    messagingSenderId: '42116415858',
    projectId: 'trash-to-cash-20037',
    databaseURL: 'https://trash-to-cash-20037-default-rtdb.firebaseio.com',
    storageBucket: 'trash-to-cash-20037.appspot.com',
    androidClientId: '42116415858-evk927j764gi4ui7jk67kmvb26avdls1.apps.googleusercontent.com',
    iosClientId: '42116415858-3dj44bq991pe7808cu0c8ut7uevjv4v3.apps.googleusercontent.com',
    iosBundleId: 'com.example.trashToCashFlutter.RunnerTests',
  );
}
